// chrome/browser/ui/webui/connectors_internals/connectors_internals.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'chrome/browser/ui/webui/connectors_internals/connectors_internals.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('connectorsInternals.mojom');



  function ZeroTrustState(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  ZeroTrustState.prototype.initDefaults_ = function() {
    this.isEnabled = false;
    this.signalsDictionary = null;
  };
  ZeroTrustState.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  ZeroTrustState.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 24}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;



    // validate ZeroTrustState.signalsDictionary
    err = messageValidator.validateMapPointer(offset + codec.kStructHeaderSize + 8, false, codec.String, codec.String, false);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  ZeroTrustState.encodedSize = codec.kStructHeaderSize + 16;

  ZeroTrustState.decode = function(decoder) {
    var packed;
    var val = new ZeroTrustState();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    packed = decoder.readUint8();
    val.isEnabled = (packed >> 0) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    val.signalsDictionary =
        decoder.decodeMapPointer(codec.String, codec.String);
    return val;
  };

  ZeroTrustState.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(ZeroTrustState.encodedSize);
    encoder.writeUint32(0);
    packed = 0;
    packed |= (val.isEnabled & 1) << 0
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.encodeMapPointer(codec.String, codec.String, val.signalsDictionary);
  };
  function PageHandler_GetZeroTrustState_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  PageHandler_GetZeroTrustState_Params.prototype.initDefaults_ = function() {
  };
  PageHandler_GetZeroTrustState_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  PageHandler_GetZeroTrustState_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  PageHandler_GetZeroTrustState_Params.encodedSize = codec.kStructHeaderSize + 0;

  PageHandler_GetZeroTrustState_Params.decode = function(decoder) {
    var packed;
    var val = new PageHandler_GetZeroTrustState_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  PageHandler_GetZeroTrustState_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(PageHandler_GetZeroTrustState_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function PageHandler_GetZeroTrustState_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  PageHandler_GetZeroTrustState_ResponseParams.prototype.initDefaults_ = function() {
    this.state = null;
  };
  PageHandler_GetZeroTrustState_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  PageHandler_GetZeroTrustState_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate PageHandler_GetZeroTrustState_ResponseParams.state
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 0, ZeroTrustState, false);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  PageHandler_GetZeroTrustState_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  PageHandler_GetZeroTrustState_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new PageHandler_GetZeroTrustState_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.state =
        decoder.decodeStructPointer(ZeroTrustState);
    return val;
  };

  PageHandler_GetZeroTrustState_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(PageHandler_GetZeroTrustState_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStructPointer(ZeroTrustState, val.state);
  };
  var kPageHandler_GetZeroTrustState_Name = 313087635;

  function PageHandlerPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(PageHandler,
                                                   handleOrPtrInfo);
  }

  function PageHandlerAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        PageHandler, associatedInterfacePtrInfo);
  }

  PageHandlerAssociatedPtr.prototype =
      Object.create(PageHandlerPtr.prototype);
  PageHandlerAssociatedPtr.prototype.constructor =
      PageHandlerAssociatedPtr;

  function PageHandlerProxy(receiver) {
    this.receiver_ = receiver;
  }
  PageHandlerPtr.prototype.getZeroTrustState = function() {
    return PageHandlerProxy.prototype.getZeroTrustState
        .apply(this.ptr.getProxy(), arguments);
  };

  PageHandlerProxy.prototype.getZeroTrustState = function() {
    var params_ = new PageHandler_GetZeroTrustState_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kPageHandler_GetZeroTrustState_Name,
          codec.align(PageHandler_GetZeroTrustState_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(PageHandler_GetZeroTrustState_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(PageHandler_GetZeroTrustState_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function PageHandlerStub(delegate) {
    this.delegate_ = delegate;
  }
  PageHandlerStub.prototype.getZeroTrustState = function() {
    return this.delegate_ && this.delegate_.getZeroTrustState && this.delegate_.getZeroTrustState();
  }

  PageHandlerStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  PageHandlerStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kPageHandler_GetZeroTrustState_Name:
      var params = reader.decodeStruct(PageHandler_GetZeroTrustState_Params);
      this.getZeroTrustState().then(function(response) {
        var responseParams =
            new PageHandler_GetZeroTrustState_ResponseParams();
        responseParams.state = response.state;
        var builder = new codec.MessageV1Builder(
            kPageHandler_GetZeroTrustState_Name,
            codec.align(PageHandler_GetZeroTrustState_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(PageHandler_GetZeroTrustState_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validatePageHandlerRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kPageHandler_GetZeroTrustState_Name:
        if (message.expectsResponse())
          paramsClass = PageHandler_GetZeroTrustState_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validatePageHandlerResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kPageHandler_GetZeroTrustState_Name:
        if (message.isResponse())
          paramsClass = PageHandler_GetZeroTrustState_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var PageHandler = {
    name: 'connectors_internals.mojom.PageHandler',
    kVersion: 0,
    ptrClass: PageHandlerPtr,
    proxyClass: PageHandlerProxy,
    stubClass: PageHandlerStub,
    validateRequest: validatePageHandlerRequest,
    validateResponse: validatePageHandlerResponse,
  };
  PageHandlerStub.prototype.validator = validatePageHandlerRequest;
  PageHandlerProxy.prototype.validator = validatePageHandlerResponse;
  exports.ZeroTrustState = ZeroTrustState;
  exports.PageHandler = PageHandler;
  exports.PageHandlerPtr = PageHandlerPtr;
  exports.PageHandlerAssociatedPtr = PageHandlerAssociatedPtr;
})();