// chrome/browser/ui/webui/federated_learning/floc_internals.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'chrome/browser/ui/webui/federated_learning/floc_internals.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('federatedLearning.mojom');
  var time$ =
      mojo.internal.exposeNamespace('mojoBase.mojom');
  if (mojo.config.autoLoadMojomDeps) {
    mojo.internal.loadMojomIfNecessary(
        'mojo/public/mojom/base/time.mojom', '../../../../../mojo/public/mojom/base/time.mojom.js');
  }



  function WebUIFlocStatus(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  WebUIFlocStatus.prototype.initDefaults_ = function() {
    this.id = null;
    this.version = null;
    this.computeTime = null;
    this.featurePagesWithAdResourcesDefaultIncludedInFlocComputation = false;
    this.featureInterestCohortApiOriginTrial = false;
    this.featureInterestCohortFeaturePolicy = false;
    this.featureParamMinimumHistoryDomainSizeRequired = 0;
    this.featureParamScheduledUpdateInterval = null;
    this.featureParamFinchConfigVersion = 0;
  };
  WebUIFlocStatus.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  WebUIFlocStatus.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 56}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIFlocStatus.id
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 0, false)
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIFlocStatus.version
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 8, false)
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIFlocStatus.computeTime
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 16, time$.Time, false);
    if (err !== validator.validationError.NONE)
        return err;





    // validate WebUIFlocStatus.featureParamScheduledUpdateInterval
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 32, time$.TimeDelta, false);
    if (err !== validator.validationError.NONE)
        return err;



    return validator.validationError.NONE;
  };

  WebUIFlocStatus.encodedSize = codec.kStructHeaderSize + 48;

  WebUIFlocStatus.decode = function(decoder) {
    var packed;
    var val = new WebUIFlocStatus();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.id =
        decoder.decodeStruct(codec.String);
    val.version =
        decoder.decodeStruct(codec.String);
    val.computeTime =
        decoder.decodeStructPointer(time$.Time);
    packed = decoder.readUint8();
    val.featurePagesWithAdResourcesDefaultIncludedInFlocComputation = (packed >> 0) & 1 ? true : false;
    val.featureInterestCohortApiOriginTrial = (packed >> 1) & 1 ? true : false;
    val.featureInterestCohortFeaturePolicy = (packed >> 2) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    val.featureParamMinimumHistoryDomainSizeRequired =
        decoder.decodeStruct(codec.Int32);
    val.featureParamScheduledUpdateInterval =
        decoder.decodeStructPointer(time$.TimeDelta);
    val.featureParamFinchConfigVersion =
        decoder.decodeStruct(codec.Int32);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  WebUIFlocStatus.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(WebUIFlocStatus.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.String, val.id);
    encoder.encodeStruct(codec.String, val.version);
    encoder.encodeStructPointer(time$.Time, val.computeTime);
    packed = 0;
    packed |= (val.featurePagesWithAdResourcesDefaultIncludedInFlocComputation & 1) << 0
    packed |= (val.featureInterestCohortApiOriginTrial & 1) << 1
    packed |= (val.featureInterestCohortFeaturePolicy & 1) << 2
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.encodeStruct(codec.Int32, val.featureParamMinimumHistoryDomainSizeRequired);
    encoder.encodeStructPointer(time$.TimeDelta, val.featureParamScheduledUpdateInterval);
    encoder.encodeStruct(codec.Int32, val.featureParamFinchConfigVersion);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function PageHandler_GetFlocStatus_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  PageHandler_GetFlocStatus_Params.prototype.initDefaults_ = function() {
  };
  PageHandler_GetFlocStatus_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  PageHandler_GetFlocStatus_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  PageHandler_GetFlocStatus_Params.encodedSize = codec.kStructHeaderSize + 0;

  PageHandler_GetFlocStatus_Params.decode = function(decoder) {
    var packed;
    var val = new PageHandler_GetFlocStatus_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  PageHandler_GetFlocStatus_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(PageHandler_GetFlocStatus_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function PageHandler_GetFlocStatus_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  PageHandler_GetFlocStatus_ResponseParams.prototype.initDefaults_ = function() {
    this.status = null;
  };
  PageHandler_GetFlocStatus_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  PageHandler_GetFlocStatus_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate PageHandler_GetFlocStatus_ResponseParams.status
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 0, WebUIFlocStatus, false);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  PageHandler_GetFlocStatus_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  PageHandler_GetFlocStatus_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new PageHandler_GetFlocStatus_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.status =
        decoder.decodeStructPointer(WebUIFlocStatus);
    return val;
  };

  PageHandler_GetFlocStatus_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(PageHandler_GetFlocStatus_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStructPointer(WebUIFlocStatus, val.status);
  };
  var kPageHandler_GetFlocStatus_Name = 313087635;

  function PageHandlerPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(PageHandler,
                                                   handleOrPtrInfo);
  }

  function PageHandlerAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        PageHandler, associatedInterfacePtrInfo);
  }

  PageHandlerAssociatedPtr.prototype =
      Object.create(PageHandlerPtr.prototype);
  PageHandlerAssociatedPtr.prototype.constructor =
      PageHandlerAssociatedPtr;

  function PageHandlerProxy(receiver) {
    this.receiver_ = receiver;
  }
  PageHandlerPtr.prototype.getFlocStatus = function() {
    return PageHandlerProxy.prototype.getFlocStatus
        .apply(this.ptr.getProxy(), arguments);
  };

  PageHandlerProxy.prototype.getFlocStatus = function() {
    var params_ = new PageHandler_GetFlocStatus_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kPageHandler_GetFlocStatus_Name,
          codec.align(PageHandler_GetFlocStatus_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(PageHandler_GetFlocStatus_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(PageHandler_GetFlocStatus_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function PageHandlerStub(delegate) {
    this.delegate_ = delegate;
  }
  PageHandlerStub.prototype.getFlocStatus = function() {
    return this.delegate_ && this.delegate_.getFlocStatus && this.delegate_.getFlocStatus();
  }

  PageHandlerStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  PageHandlerStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kPageHandler_GetFlocStatus_Name:
      var params = reader.decodeStruct(PageHandler_GetFlocStatus_Params);
      this.getFlocStatus().then(function(response) {
        var responseParams =
            new PageHandler_GetFlocStatus_ResponseParams();
        responseParams.status = response.status;
        var builder = new codec.MessageV1Builder(
            kPageHandler_GetFlocStatus_Name,
            codec.align(PageHandler_GetFlocStatus_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(PageHandler_GetFlocStatus_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validatePageHandlerRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kPageHandler_GetFlocStatus_Name:
        if (message.expectsResponse())
          paramsClass = PageHandler_GetFlocStatus_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validatePageHandlerResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kPageHandler_GetFlocStatus_Name:
        if (message.isResponse())
          paramsClass = PageHandler_GetFlocStatus_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var PageHandler = {
    name: 'federated_learning.mojom.PageHandler',
    kVersion: 0,
    ptrClass: PageHandlerPtr,
    proxyClass: PageHandlerProxy,
    stubClass: PageHandlerStub,
    validateRequest: validatePageHandlerRequest,
    validateResponse: validatePageHandlerResponse,
  };
  PageHandlerStub.prototype.validator = validatePageHandlerRequest;
  PageHandlerProxy.prototype.validator = validatePageHandlerResponse;
  exports.WebUIFlocStatus = WebUIFlocStatus;
  exports.PageHandler = PageHandler;
  exports.PageHandlerPtr = PageHandlerPtr;
  exports.PageHandlerAssociatedPtr = PageHandlerAssociatedPtr;
})();