// content/browser/attribution_reporting/attribution_internals.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'content/browser/attribution_reporting/attribution_internals.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('content.mojom');
  var origin$ =
      mojo.internal.exposeNamespace('url.mojom');
  if (mojo.config.autoLoadMojomDeps) {
    mojo.internal.loadMojomIfNecessary(
        'url/mojom/origin.mojom', '../../../url/mojom/origin.mojom.js');
  }
  var url$ =
      mojo.internal.exposeNamespace('url.mojom');
  if (mojo.config.autoLoadMojomDeps) {
    mojo.internal.loadMojomIfNecessary(
        'url/mojom/url.mojom', '../../../url/mojom/url.mojom.js');
  }


  var SourceType = {};
  SourceType.kNavigation = 0;
  SourceType.kEvent = 1;
  SourceType.MIN_VALUE = 0;
  SourceType.MAX_VALUE = 1;

  SourceType.isKnownEnumValue = function(value) {
    switch (value) {
    case 0:
    case 1:
      return true;
    }
    return false;
  };

  SourceType.toKnownEnumValue = function(value) {
    return value;
  };

  SourceType.validate = function(enumValue) {
    const isExtensible = false;
    if (isExtensible || this.isKnownEnumValue(enumValue))
      return validator.validationError.NONE;

    return validator.validationError.UNKNOWN_ENUM_VALUE;
  };

  function WebUIConversionReport(values) {
    this.initDefaults_();
    this.initFields_(values);
  }

  WebUIConversionReport.Status = {};
  WebUIConversionReport.Status.kPending = 0;
  WebUIConversionReport.Status.kDroppedDueToLowPriority = 1;
  WebUIConversionReport.Status.kDroppedForNoise = 2;
  WebUIConversionReport.Status.kSent = 3;
  WebUIConversionReport.Status.MIN_VALUE = 0;
  WebUIConversionReport.Status.MAX_VALUE = 3;

  WebUIConversionReport.Status.isKnownEnumValue = function(value) {
    switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    }
    return false;
  };

  WebUIConversionReport.Status.toKnownEnumValue = function(value) {
    return value;
  };

  WebUIConversionReport.Status.validate = function(enumValue) {
    const isExtensible = false;
    if (isExtensible || this.isKnownEnumValue(enumValue))
      return validator.validationError.NONE;

    return validator.validationError.UNKNOWN_ENUM_VALUE;
  };

  WebUIConversionReport.prototype.initDefaults_ = function() {
    this.conversionOrigin = null;
    this.reportUrl = null;
    this.triggerTime = 0;
    this.reportTime = 0;
    this.priority = 0;
    this.reportBody = null;
    this.attributedTruthfully = false;
    this.status = 0;
    this.httpResponseCode = 0;
  };
  WebUIConversionReport.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  WebUIConversionReport.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 72}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIConversionReport.conversionOrigin
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 0, origin$.Origin, false);
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIConversionReport.reportUrl
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 8, url$.Url, false);
    if (err !== validator.validationError.NONE)
        return err;





    // validate WebUIConversionReport.reportBody
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 40, false)
    if (err !== validator.validationError.NONE)
        return err;



    // validate WebUIConversionReport.status
    err = messageValidator.validateEnum(offset + codec.kStructHeaderSize + 52, WebUIConversionReport.Status);
    if (err !== validator.validationError.NONE)
        return err;


    return validator.validationError.NONE;
  };

  WebUIConversionReport.encodedSize = codec.kStructHeaderSize + 64;

  WebUIConversionReport.decode = function(decoder) {
    var packed;
    var val = new WebUIConversionReport();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.conversionOrigin =
        decoder.decodeStructPointer(origin$.Origin);
    val.reportUrl =
        decoder.decodeStructPointer(url$.Url);
    val.triggerTime =
        decoder.decodeStruct(codec.Double);
    val.reportTime =
        decoder.decodeStruct(codec.Double);
    val.priority =
        decoder.decodeStruct(codec.Int64);
    val.reportBody =
        decoder.decodeStruct(codec.String);
    packed = decoder.readUint8();
    val.attributedTruthfully = (packed >> 0) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    val.status =
        decoder.decodeStruct(new codec.Enum(WebUIConversionReport.Status));
    val.httpResponseCode =
        decoder.decodeStruct(codec.Int32);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  WebUIConversionReport.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(WebUIConversionReport.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStructPointer(origin$.Origin, val.conversionOrigin);
    encoder.encodeStructPointer(url$.Url, val.reportUrl);
    encoder.encodeStruct(codec.Double, val.triggerTime);
    encoder.encodeStruct(codec.Double, val.reportTime);
    encoder.encodeStruct(codec.Int64, val.priority);
    encoder.encodeStruct(codec.String, val.reportBody);
    packed = 0;
    packed |= (val.attributedTruthfully & 1) << 0
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.encodeStruct(codec.Int32, val.status);
    encoder.encodeStruct(codec.Int32, val.httpResponseCode);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function WebUIImpression(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  WebUIImpression.prototype.initDefaults_ = function() {
    this.impressionData = 0;
    this.impressionOrigin = null;
    this.conversionDestination = null;
    this.reportingOrigin = null;
    this.impressionTime = 0;
    this.expiryTime = 0;
    this.sourceType = 0;
    this.reportable = false;
    this.priority = 0;
    this.dedupKeys = null;
  };
  WebUIImpression.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  WebUIImpression.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 80}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;



    // validate WebUIImpression.impressionOrigin
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 8, origin$.Origin, false);
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIImpression.conversionDestination
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 16, origin$.Origin, false);
    if (err !== validator.validationError.NONE)
        return err;


    // validate WebUIImpression.reportingOrigin
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 24, origin$.Origin, false);
    if (err !== validator.validationError.NONE)
        return err;




    // validate WebUIImpression.sourceType
    err = messageValidator.validateEnum(offset + codec.kStructHeaderSize + 48, SourceType);
    if (err !== validator.validationError.NONE)
        return err;



    // validate WebUIImpression.dedupKeys
    err = messageValidator.validateArrayPointer(offset + codec.kStructHeaderSize + 64, 8, codec.Int64, false, [0], 0);
    if (err !== validator.validationError.NONE)
        return err;


    return validator.validationError.NONE;
  };

  WebUIImpression.encodedSize = codec.kStructHeaderSize + 72;

  WebUIImpression.decode = function(decoder) {
    var packed;
    var val = new WebUIImpression();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.impressionData =
        decoder.decodeStruct(codec.Uint64);
    val.impressionOrigin =
        decoder.decodeStructPointer(origin$.Origin);
    val.conversionDestination =
        decoder.decodeStructPointer(origin$.Origin);
    val.reportingOrigin =
        decoder.decodeStructPointer(origin$.Origin);
    val.impressionTime =
        decoder.decodeStruct(codec.Double);
    val.expiryTime =
        decoder.decodeStruct(codec.Double);
    val.sourceType =
        decoder.decodeStruct(new codec.Enum(SourceType));
    packed = decoder.readUint8();
    val.reportable = (packed >> 0) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    val.priority =
        decoder.decodeStruct(codec.Int64);
    val.dedupKeys =
        decoder.decodeArrayPointer(codec.Int64);
    return val;
  };

  WebUIImpression.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(WebUIImpression.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.Uint64, val.impressionData);
    encoder.encodeStructPointer(origin$.Origin, val.impressionOrigin);
    encoder.encodeStructPointer(origin$.Origin, val.conversionDestination);
    encoder.encodeStructPointer(origin$.Origin, val.reportingOrigin);
    encoder.encodeStruct(codec.Double, val.impressionTime);
    encoder.encodeStruct(codec.Double, val.expiryTime);
    encoder.encodeStruct(codec.Int32, val.sourceType);
    packed = 0;
    packed |= (val.reportable & 1) << 0
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.encodeStruct(codec.Int64, val.priority);
    encoder.encodeArrayPointer(codec.Int64, val.dedupKeys);
  };
  function AttributionInternalsHandler_IsMeasurementEnabled_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_IsMeasurementEnabled_Params.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_IsMeasurementEnabled_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_IsMeasurementEnabled_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_IsMeasurementEnabled_Params.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_IsMeasurementEnabled_Params.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_IsMeasurementEnabled_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_IsMeasurementEnabled_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_IsMeasurementEnabled_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.prototype.initDefaults_ = function() {
    this.enabled = false;
    this.debugMode = false;
  };
  AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;



    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    packed = decoder.readUint8();
    val.enabled = (packed >> 0) & 1 ? true : false;
    val.debugMode = (packed >> 1) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    packed = 0;
    packed |= (val.enabled & 1) << 0
    packed |= (val.debugMode & 1) << 1
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function AttributionInternalsHandler_GetActiveImpressions_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_GetActiveImpressions_Params.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_GetActiveImpressions_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_GetActiveImpressions_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_GetActiveImpressions_Params.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_GetActiveImpressions_Params.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_GetActiveImpressions_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_GetActiveImpressions_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_GetActiveImpressions_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function AttributionInternalsHandler_GetActiveImpressions_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_GetActiveImpressions_ResponseParams.prototype.initDefaults_ = function() {
    this.impressions = null;
  };
  AttributionInternalsHandler_GetActiveImpressions_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_GetActiveImpressions_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate AttributionInternalsHandler_GetActiveImpressions_ResponseParams.impressions
    err = messageValidator.validateArrayPointer(offset + codec.kStructHeaderSize + 0, 8, new codec.PointerTo(WebUIImpression), false, [0], 0);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_GetActiveImpressions_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  AttributionInternalsHandler_GetActiveImpressions_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_GetActiveImpressions_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.impressions =
        decoder.decodeArrayPointer(new codec.PointerTo(WebUIImpression));
    return val;
  };

  AttributionInternalsHandler_GetActiveImpressions_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_GetActiveImpressions_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeArrayPointer(new codec.PointerTo(WebUIImpression), val.impressions);
  };
  function AttributionInternalsHandler_GetReports_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_GetReports_Params.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_GetReports_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_GetReports_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_GetReports_Params.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_GetReports_Params.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_GetReports_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_GetReports_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_GetReports_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function AttributionInternalsHandler_GetReports_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_GetReports_ResponseParams.prototype.initDefaults_ = function() {
    this.reports = null;
  };
  AttributionInternalsHandler_GetReports_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_GetReports_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate AttributionInternalsHandler_GetReports_ResponseParams.reports
    err = messageValidator.validateArrayPointer(offset + codec.kStructHeaderSize + 0, 8, new codec.PointerTo(WebUIConversionReport), false, [0], 0);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_GetReports_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  AttributionInternalsHandler_GetReports_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_GetReports_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.reports =
        decoder.decodeArrayPointer(new codec.PointerTo(WebUIConversionReport));
    return val;
  };

  AttributionInternalsHandler_GetReports_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_GetReports_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeArrayPointer(new codec.PointerTo(WebUIConversionReport), val.reports);
  };
  function AttributionInternalsHandler_SendPendingReports_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_SendPendingReports_Params.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_SendPendingReports_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_SendPendingReports_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_SendPendingReports_Params.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_SendPendingReports_Params.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_SendPendingReports_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_SendPendingReports_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_SendPendingReports_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function AttributionInternalsHandler_SendPendingReports_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_SendPendingReports_ResponseParams.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_SendPendingReports_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_SendPendingReports_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_SendPendingReports_ResponseParams.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_SendPendingReports_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_SendPendingReports_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_SendPendingReports_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_SendPendingReports_ResponseParams.encodedSize);
    encoder.writeUint32(0);
  };
  function AttributionInternalsHandler_ClearStorage_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_ClearStorage_Params.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_ClearStorage_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_ClearStorage_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_ClearStorage_Params.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_ClearStorage_Params.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_ClearStorage_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_ClearStorage_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_ClearStorage_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function AttributionInternalsHandler_ClearStorage_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  AttributionInternalsHandler_ClearStorage_ResponseParams.prototype.initDefaults_ = function() {
  };
  AttributionInternalsHandler_ClearStorage_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  AttributionInternalsHandler_ClearStorage_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  AttributionInternalsHandler_ClearStorage_ResponseParams.encodedSize = codec.kStructHeaderSize + 0;

  AttributionInternalsHandler_ClearStorage_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new AttributionInternalsHandler_ClearStorage_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  AttributionInternalsHandler_ClearStorage_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(AttributionInternalsHandler_ClearStorage_ResponseParams.encodedSize);
    encoder.writeUint32(0);
  };
  var kAttributionInternalsHandler_IsMeasurementEnabled_Name = 947856844;
  var kAttributionInternalsHandler_GetActiveImpressions_Name = 554694241;
  var kAttributionInternalsHandler_GetReports_Name = 1856095203;
  var kAttributionInternalsHandler_SendPendingReports_Name = 89711911;
  var kAttributionInternalsHandler_ClearStorage_Name = 659176381;

  function AttributionInternalsHandlerPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(AttributionInternalsHandler,
                                                   handleOrPtrInfo);
  }

  function AttributionInternalsHandlerAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        AttributionInternalsHandler, associatedInterfacePtrInfo);
  }

  AttributionInternalsHandlerAssociatedPtr.prototype =
      Object.create(AttributionInternalsHandlerPtr.prototype);
  AttributionInternalsHandlerAssociatedPtr.prototype.constructor =
      AttributionInternalsHandlerAssociatedPtr;

  function AttributionInternalsHandlerProxy(receiver) {
    this.receiver_ = receiver;
  }
  AttributionInternalsHandlerPtr.prototype.isMeasurementEnabled = function() {
    return AttributionInternalsHandlerProxy.prototype.isMeasurementEnabled
        .apply(this.ptr.getProxy(), arguments);
  };

  AttributionInternalsHandlerProxy.prototype.isMeasurementEnabled = function() {
    var params_ = new AttributionInternalsHandler_IsMeasurementEnabled_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kAttributionInternalsHandler_IsMeasurementEnabled_Name,
          codec.align(AttributionInternalsHandler_IsMeasurementEnabled_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(AttributionInternalsHandler_IsMeasurementEnabled_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };
  AttributionInternalsHandlerPtr.prototype.getActiveImpressions = function() {
    return AttributionInternalsHandlerProxy.prototype.getActiveImpressions
        .apply(this.ptr.getProxy(), arguments);
  };

  AttributionInternalsHandlerProxy.prototype.getActiveImpressions = function() {
    var params_ = new AttributionInternalsHandler_GetActiveImpressions_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kAttributionInternalsHandler_GetActiveImpressions_Name,
          codec.align(AttributionInternalsHandler_GetActiveImpressions_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(AttributionInternalsHandler_GetActiveImpressions_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(AttributionInternalsHandler_GetActiveImpressions_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };
  AttributionInternalsHandlerPtr.prototype.getReports = function() {
    return AttributionInternalsHandlerProxy.prototype.getReports
        .apply(this.ptr.getProxy(), arguments);
  };

  AttributionInternalsHandlerProxy.prototype.getReports = function() {
    var params_ = new AttributionInternalsHandler_GetReports_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kAttributionInternalsHandler_GetReports_Name,
          codec.align(AttributionInternalsHandler_GetReports_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(AttributionInternalsHandler_GetReports_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(AttributionInternalsHandler_GetReports_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };
  AttributionInternalsHandlerPtr.prototype.sendPendingReports = function() {
    return AttributionInternalsHandlerProxy.prototype.sendPendingReports
        .apply(this.ptr.getProxy(), arguments);
  };

  AttributionInternalsHandlerProxy.prototype.sendPendingReports = function() {
    var params_ = new AttributionInternalsHandler_SendPendingReports_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kAttributionInternalsHandler_SendPendingReports_Name,
          codec.align(AttributionInternalsHandler_SendPendingReports_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(AttributionInternalsHandler_SendPendingReports_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(AttributionInternalsHandler_SendPendingReports_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };
  AttributionInternalsHandlerPtr.prototype.clearStorage = function() {
    return AttributionInternalsHandlerProxy.prototype.clearStorage
        .apply(this.ptr.getProxy(), arguments);
  };

  AttributionInternalsHandlerProxy.prototype.clearStorage = function() {
    var params_ = new AttributionInternalsHandler_ClearStorage_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kAttributionInternalsHandler_ClearStorage_Name,
          codec.align(AttributionInternalsHandler_ClearStorage_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(AttributionInternalsHandler_ClearStorage_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(AttributionInternalsHandler_ClearStorage_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function AttributionInternalsHandlerStub(delegate) {
    this.delegate_ = delegate;
  }
  AttributionInternalsHandlerStub.prototype.isMeasurementEnabled = function() {
    return this.delegate_ && this.delegate_.isMeasurementEnabled && this.delegate_.isMeasurementEnabled();
  }
  AttributionInternalsHandlerStub.prototype.getActiveImpressions = function() {
    return this.delegate_ && this.delegate_.getActiveImpressions && this.delegate_.getActiveImpressions();
  }
  AttributionInternalsHandlerStub.prototype.getReports = function() {
    return this.delegate_ && this.delegate_.getReports && this.delegate_.getReports();
  }
  AttributionInternalsHandlerStub.prototype.sendPendingReports = function() {
    return this.delegate_ && this.delegate_.sendPendingReports && this.delegate_.sendPendingReports();
  }
  AttributionInternalsHandlerStub.prototype.clearStorage = function() {
    return this.delegate_ && this.delegate_.clearStorage && this.delegate_.clearStorage();
  }

  AttributionInternalsHandlerStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  AttributionInternalsHandlerStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kAttributionInternalsHandler_IsMeasurementEnabled_Name:
      var params = reader.decodeStruct(AttributionInternalsHandler_IsMeasurementEnabled_Params);
      this.isMeasurementEnabled().then(function(response) {
        var responseParams =
            new AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams();
        responseParams.enabled = response.enabled;
        responseParams.debugMode = response.debugMode;
        var builder = new codec.MessageV1Builder(
            kAttributionInternalsHandler_IsMeasurementEnabled_Name,
            codec.align(AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    case kAttributionInternalsHandler_GetActiveImpressions_Name:
      var params = reader.decodeStruct(AttributionInternalsHandler_GetActiveImpressions_Params);
      this.getActiveImpressions().then(function(response) {
        var responseParams =
            new AttributionInternalsHandler_GetActiveImpressions_ResponseParams();
        responseParams.impressions = response.impressions;
        var builder = new codec.MessageV1Builder(
            kAttributionInternalsHandler_GetActiveImpressions_Name,
            codec.align(AttributionInternalsHandler_GetActiveImpressions_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(AttributionInternalsHandler_GetActiveImpressions_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    case kAttributionInternalsHandler_GetReports_Name:
      var params = reader.decodeStruct(AttributionInternalsHandler_GetReports_Params);
      this.getReports().then(function(response) {
        var responseParams =
            new AttributionInternalsHandler_GetReports_ResponseParams();
        responseParams.reports = response.reports;
        var builder = new codec.MessageV1Builder(
            kAttributionInternalsHandler_GetReports_Name,
            codec.align(AttributionInternalsHandler_GetReports_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(AttributionInternalsHandler_GetReports_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    case kAttributionInternalsHandler_SendPendingReports_Name:
      var params = reader.decodeStruct(AttributionInternalsHandler_SendPendingReports_Params);
      this.sendPendingReports().then(function(response) {
        var responseParams =
            new AttributionInternalsHandler_SendPendingReports_ResponseParams();
        var builder = new codec.MessageV1Builder(
            kAttributionInternalsHandler_SendPendingReports_Name,
            codec.align(AttributionInternalsHandler_SendPendingReports_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(AttributionInternalsHandler_SendPendingReports_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    case kAttributionInternalsHandler_ClearStorage_Name:
      var params = reader.decodeStruct(AttributionInternalsHandler_ClearStorage_Params);
      this.clearStorage().then(function(response) {
        var responseParams =
            new AttributionInternalsHandler_ClearStorage_ResponseParams();
        var builder = new codec.MessageV1Builder(
            kAttributionInternalsHandler_ClearStorage_Name,
            codec.align(AttributionInternalsHandler_ClearStorage_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(AttributionInternalsHandler_ClearStorage_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validateAttributionInternalsHandlerRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kAttributionInternalsHandler_IsMeasurementEnabled_Name:
        if (message.expectsResponse())
          paramsClass = AttributionInternalsHandler_IsMeasurementEnabled_Params;
      break;
      case kAttributionInternalsHandler_GetActiveImpressions_Name:
        if (message.expectsResponse())
          paramsClass = AttributionInternalsHandler_GetActiveImpressions_Params;
      break;
      case kAttributionInternalsHandler_GetReports_Name:
        if (message.expectsResponse())
          paramsClass = AttributionInternalsHandler_GetReports_Params;
      break;
      case kAttributionInternalsHandler_SendPendingReports_Name:
        if (message.expectsResponse())
          paramsClass = AttributionInternalsHandler_SendPendingReports_Params;
      break;
      case kAttributionInternalsHandler_ClearStorage_Name:
        if (message.expectsResponse())
          paramsClass = AttributionInternalsHandler_ClearStorage_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validateAttributionInternalsHandlerResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kAttributionInternalsHandler_IsMeasurementEnabled_Name:
        if (message.isResponse())
          paramsClass = AttributionInternalsHandler_IsMeasurementEnabled_ResponseParams;
        break;
      case kAttributionInternalsHandler_GetActiveImpressions_Name:
        if (message.isResponse())
          paramsClass = AttributionInternalsHandler_GetActiveImpressions_ResponseParams;
        break;
      case kAttributionInternalsHandler_GetReports_Name:
        if (message.isResponse())
          paramsClass = AttributionInternalsHandler_GetReports_ResponseParams;
        break;
      case kAttributionInternalsHandler_SendPendingReports_Name:
        if (message.isResponse())
          paramsClass = AttributionInternalsHandler_SendPendingReports_ResponseParams;
        break;
      case kAttributionInternalsHandler_ClearStorage_Name:
        if (message.isResponse())
          paramsClass = AttributionInternalsHandler_ClearStorage_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var AttributionInternalsHandler = {
    name: 'content.mojom.AttributionInternalsHandler',
    kVersion: 0,
    ptrClass: AttributionInternalsHandlerPtr,
    proxyClass: AttributionInternalsHandlerProxy,
    stubClass: AttributionInternalsHandlerStub,
    validateRequest: validateAttributionInternalsHandlerRequest,
    validateResponse: validateAttributionInternalsHandlerResponse,
  };
  AttributionInternalsHandlerStub.prototype.validator = validateAttributionInternalsHandlerRequest;
  AttributionInternalsHandlerProxy.prototype.validator = validateAttributionInternalsHandlerResponse;
  exports.SourceType = SourceType;
  exports.WebUIConversionReport = WebUIConversionReport;
  exports.WebUIImpression = WebUIImpression;
  exports.AttributionInternalsHandler = AttributionInternalsHandler;
  exports.AttributionInternalsHandlerPtr = AttributionInternalsHandlerPtr;
  exports.AttributionInternalsHandlerAssociatedPtr = AttributionInternalsHandlerAssociatedPtr;
})();