// chrome/browser/search/drive/drive.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'chrome/browser/search/drive/drive.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('drive.mojom');


  var FileType = {};
  FileType.kDoc = 0;
  FileType.kSlide = 1;
  FileType.kSheet = 2;
  FileType.kOther = 3;
  FileType.MIN_VALUE = 0;
  FileType.MAX_VALUE = 3;

  FileType.isKnownEnumValue = function(value) {
    switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    }
    return false;
  };

  FileType.toKnownEnumValue = function(value) {
    return value;
  };

  FileType.validate = function(enumValue) {
    const isExtensible = false;
    if (isExtensible || this.isKnownEnumValue(enumValue))
      return validator.validationError.NONE;

    return validator.validationError.UNKNOWN_ENUM_VALUE;
  };

  function File(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  File.prototype.initDefaults_ = function() {
    this.id = null;
    this.justificationText = null;
    this.title = null;
    this.type = 0;
  };
  File.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  File.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 40}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate File.id
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 0, false)
    if (err !== validator.validationError.NONE)
        return err;


    // validate File.justificationText
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 8, false)
    if (err !== validator.validationError.NONE)
        return err;


    // validate File.title
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 16, false)
    if (err !== validator.validationError.NONE)
        return err;


    // validate File.type
    err = messageValidator.validateEnum(offset + codec.kStructHeaderSize + 24, FileType);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  File.encodedSize = codec.kStructHeaderSize + 32;

  File.decode = function(decoder) {
    var packed;
    var val = new File();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.id =
        decoder.decodeStruct(codec.String);
    val.justificationText =
        decoder.decodeStruct(codec.String);
    val.title =
        decoder.decodeStruct(codec.String);
    val.type =
        decoder.decodeStruct(new codec.Enum(FileType));
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  File.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(File.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.String, val.id);
    encoder.encodeStruct(codec.String, val.justificationText);
    encoder.encodeStruct(codec.String, val.title);
    encoder.encodeStruct(codec.Int32, val.type);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function DriveHandler_GetFiles_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  DriveHandler_GetFiles_Params.prototype.initDefaults_ = function() {
  };
  DriveHandler_GetFiles_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  DriveHandler_GetFiles_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  DriveHandler_GetFiles_Params.encodedSize = codec.kStructHeaderSize + 0;

  DriveHandler_GetFiles_Params.decode = function(decoder) {
    var packed;
    var val = new DriveHandler_GetFiles_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  DriveHandler_GetFiles_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(DriveHandler_GetFiles_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function DriveHandler_GetFiles_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  DriveHandler_GetFiles_ResponseParams.prototype.initDefaults_ = function() {
    this.files = null;
  };
  DriveHandler_GetFiles_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  DriveHandler_GetFiles_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate DriveHandler_GetFiles_ResponseParams.files
    err = messageValidator.validateArrayPointer(offset + codec.kStructHeaderSize + 0, 8, new codec.PointerTo(File), false, [0], 0);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  DriveHandler_GetFiles_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  DriveHandler_GetFiles_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new DriveHandler_GetFiles_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.files =
        decoder.decodeArrayPointer(new codec.PointerTo(File));
    return val;
  };

  DriveHandler_GetFiles_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(DriveHandler_GetFiles_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeArrayPointer(new codec.PointerTo(File), val.files);
  };
  var kDriveHandler_GetFiles_Name = 948403159;

  function DriveHandlerPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(DriveHandler,
                                                   handleOrPtrInfo);
  }

  function DriveHandlerAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        DriveHandler, associatedInterfacePtrInfo);
  }

  DriveHandlerAssociatedPtr.prototype =
      Object.create(DriveHandlerPtr.prototype);
  DriveHandlerAssociatedPtr.prototype.constructor =
      DriveHandlerAssociatedPtr;

  function DriveHandlerProxy(receiver) {
    this.receiver_ = receiver;
  }
  DriveHandlerPtr.prototype.getFiles = function() {
    return DriveHandlerProxy.prototype.getFiles
        .apply(this.ptr.getProxy(), arguments);
  };

  DriveHandlerProxy.prototype.getFiles = function() {
    var params_ = new DriveHandler_GetFiles_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kDriveHandler_GetFiles_Name,
          codec.align(DriveHandler_GetFiles_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(DriveHandler_GetFiles_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(DriveHandler_GetFiles_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function DriveHandlerStub(delegate) {
    this.delegate_ = delegate;
  }
  DriveHandlerStub.prototype.getFiles = function() {
    return this.delegate_ && this.delegate_.getFiles && this.delegate_.getFiles();
  }

  DriveHandlerStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  DriveHandlerStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kDriveHandler_GetFiles_Name:
      var params = reader.decodeStruct(DriveHandler_GetFiles_Params);
      this.getFiles().then(function(response) {
        var responseParams =
            new DriveHandler_GetFiles_ResponseParams();
        responseParams.files = response.files;
        var builder = new codec.MessageV1Builder(
            kDriveHandler_GetFiles_Name,
            codec.align(DriveHandler_GetFiles_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(DriveHandler_GetFiles_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validateDriveHandlerRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kDriveHandler_GetFiles_Name:
        if (message.expectsResponse())
          paramsClass = DriveHandler_GetFiles_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validateDriveHandlerResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kDriveHandler_GetFiles_Name:
        if (message.isResponse())
          paramsClass = DriveHandler_GetFiles_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var DriveHandler = {
    name: 'drive.mojom.DriveHandler',
    kVersion: 0,
    ptrClass: DriveHandlerPtr,
    proxyClass: DriveHandlerProxy,
    stubClass: DriveHandlerStub,
    validateRequest: validateDriveHandlerRequest,
    validateResponse: validateDriveHandlerResponse,
  };
  DriveHandlerStub.prototype.validator = validateDriveHandlerRequest;
  DriveHandlerProxy.prototype.validator = validateDriveHandlerResponse;
  exports.FileType = FileType;
  exports.File = File;
  exports.DriveHandler = DriveHandler;
  exports.DriveHandlerPtr = DriveHandlerPtr;
  exports.DriveHandlerAssociatedPtr = DriveHandlerAssociatedPtr;
})();