// ui/webui/resources/js/browser_command/browser_command.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'ui/webui/resources/js/browser_command/browser_command.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('browserCommand.mojom');


  var Command = {};
  Command.kUnknownCommand = 0;
  Command.kOpenSafetyCheck = 1;
  Command.kOpenSafeBrowsingEnhancedProtectionSettings = 2;
  Command.kOpenFeedbackForm = 3;
  Command.MIN_VALUE = 0;
  Command.MAX_VALUE = 3;

  Command.isKnownEnumValue = function(value) {
    switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    }
    return false;
  };

  Command.toKnownEnumValue = function(value) {
    return value;
  };

  Command.validate = function(enumValue) {
    const isExtensible = false;
    if (isExtensible || this.isKnownEnumValue(enumValue))
      return validator.validationError.NONE;

    return validator.validationError.UNKNOWN_ENUM_VALUE;
  };

  function ClickInfo(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  ClickInfo.prototype.initDefaults_ = function() {
    this.middleButton = false;
    this.altKey = false;
    this.ctrlKey = false;
    this.metaKey = false;
    this.shiftKey = false;
  };
  ClickInfo.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  ClickInfo.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;






    return validator.validationError.NONE;
  };

  ClickInfo.encodedSize = codec.kStructHeaderSize + 8;

  ClickInfo.decode = function(decoder) {
    var packed;
    var val = new ClickInfo();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    packed = decoder.readUint8();
    val.middleButton = (packed >> 0) & 1 ? true : false;
    val.altKey = (packed >> 1) & 1 ? true : false;
    val.ctrlKey = (packed >> 2) & 1 ? true : false;
    val.metaKey = (packed >> 3) & 1 ? true : false;
    val.shiftKey = (packed >> 4) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  ClickInfo.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(ClickInfo.encodedSize);
    encoder.writeUint32(0);
    packed = 0;
    packed |= (val.middleButton & 1) << 0
    packed |= (val.altKey & 1) << 1
    packed |= (val.ctrlKey & 1) << 2
    packed |= (val.metaKey & 1) << 3
    packed |= (val.shiftKey & 1) << 4
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function CommandHandlerFactory_CreateBrowserCommandHandler_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  CommandHandlerFactory_CreateBrowserCommandHandler_Params.prototype.initDefaults_ = function() {
    this.handler = new bindings.InterfaceRequest();
  };
  CommandHandlerFactory_CreateBrowserCommandHandler_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  CommandHandlerFactory_CreateBrowserCommandHandler_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate CommandHandlerFactory_CreateBrowserCommandHandler_Params.handler
    err = messageValidator.validateInterfaceRequest(offset + codec.kStructHeaderSize + 0, false)
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  CommandHandlerFactory_CreateBrowserCommandHandler_Params.encodedSize = codec.kStructHeaderSize + 8;

  CommandHandlerFactory_CreateBrowserCommandHandler_Params.decode = function(decoder) {
    var packed;
    var val = new CommandHandlerFactory_CreateBrowserCommandHandler_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.handler =
        decoder.decodeStruct(codec.InterfaceRequest);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  CommandHandlerFactory_CreateBrowserCommandHandler_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(CommandHandlerFactory_CreateBrowserCommandHandler_Params.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.InterfaceRequest, val.handler);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function CommandHandler_CanExecuteCommand_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  CommandHandler_CanExecuteCommand_Params.prototype.initDefaults_ = function() {
    this.commandId = 0;
  };
  CommandHandler_CanExecuteCommand_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  CommandHandler_CanExecuteCommand_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate CommandHandler_CanExecuteCommand_Params.commandId
    err = messageValidator.validateEnum(offset + codec.kStructHeaderSize + 0, Command);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  CommandHandler_CanExecuteCommand_Params.encodedSize = codec.kStructHeaderSize + 8;

  CommandHandler_CanExecuteCommand_Params.decode = function(decoder) {
    var packed;
    var val = new CommandHandler_CanExecuteCommand_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.commandId =
        decoder.decodeStruct(new codec.Enum(Command));
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  CommandHandler_CanExecuteCommand_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(CommandHandler_CanExecuteCommand_Params.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.Int32, val.commandId);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function CommandHandler_CanExecuteCommand_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  CommandHandler_CanExecuteCommand_ResponseParams.prototype.initDefaults_ = function() {
    this.canExecute = false;
  };
  CommandHandler_CanExecuteCommand_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  CommandHandler_CanExecuteCommand_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    return validator.validationError.NONE;
  };

  CommandHandler_CanExecuteCommand_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  CommandHandler_CanExecuteCommand_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new CommandHandler_CanExecuteCommand_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    packed = decoder.readUint8();
    val.canExecute = (packed >> 0) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  CommandHandler_CanExecuteCommand_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(CommandHandler_CanExecuteCommand_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    packed = 0;
    packed |= (val.canExecute & 1) << 0
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function CommandHandler_ExecuteCommand_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  CommandHandler_ExecuteCommand_Params.prototype.initDefaults_ = function() {
    this.commandId = 0;
    this.clickInfo = null;
  };
  CommandHandler_ExecuteCommand_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  CommandHandler_ExecuteCommand_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 24}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate CommandHandler_ExecuteCommand_Params.commandId
    err = messageValidator.validateEnum(offset + codec.kStructHeaderSize + 0, Command);
    if (err !== validator.validationError.NONE)
        return err;


    // validate CommandHandler_ExecuteCommand_Params.clickInfo
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 8, ClickInfo, false);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  CommandHandler_ExecuteCommand_Params.encodedSize = codec.kStructHeaderSize + 16;

  CommandHandler_ExecuteCommand_Params.decode = function(decoder) {
    var packed;
    var val = new CommandHandler_ExecuteCommand_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.commandId =
        decoder.decodeStruct(new codec.Enum(Command));
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    val.clickInfo =
        decoder.decodeStructPointer(ClickInfo);
    return val;
  };

  CommandHandler_ExecuteCommand_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(CommandHandler_ExecuteCommand_Params.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.Int32, val.commandId);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.encodeStructPointer(ClickInfo, val.clickInfo);
  };
  function CommandHandler_ExecuteCommand_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  CommandHandler_ExecuteCommand_ResponseParams.prototype.initDefaults_ = function() {
    this.commandExecuted = false;
  };
  CommandHandler_ExecuteCommand_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  CommandHandler_ExecuteCommand_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    return validator.validationError.NONE;
  };

  CommandHandler_ExecuteCommand_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  CommandHandler_ExecuteCommand_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new CommandHandler_ExecuteCommand_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    packed = decoder.readUint8();
    val.commandExecuted = (packed >> 0) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  CommandHandler_ExecuteCommand_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(CommandHandler_ExecuteCommand_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    packed = 0;
    packed |= (val.commandExecuted & 1) << 0
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  var kCommandHandlerFactory_CreateBrowserCommandHandler_Name = 1276860413;

  function CommandHandlerFactoryPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(CommandHandlerFactory,
                                                   handleOrPtrInfo);
  }

  function CommandHandlerFactoryAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        CommandHandlerFactory, associatedInterfacePtrInfo);
  }

  CommandHandlerFactoryAssociatedPtr.prototype =
      Object.create(CommandHandlerFactoryPtr.prototype);
  CommandHandlerFactoryAssociatedPtr.prototype.constructor =
      CommandHandlerFactoryAssociatedPtr;

  function CommandHandlerFactoryProxy(receiver) {
    this.receiver_ = receiver;
  }
  CommandHandlerFactoryPtr.prototype.createBrowserCommandHandler = function() {
    return CommandHandlerFactoryProxy.prototype.createBrowserCommandHandler
        .apply(this.ptr.getProxy(), arguments);
  };

  CommandHandlerFactoryProxy.prototype.createBrowserCommandHandler = function(handler) {
    var params_ = new CommandHandlerFactory_CreateBrowserCommandHandler_Params();
    params_.handler = handler;
    var builder = new codec.MessageV0Builder(
        kCommandHandlerFactory_CreateBrowserCommandHandler_Name,
        codec.align(CommandHandlerFactory_CreateBrowserCommandHandler_Params.encodedSize));
    builder.encodeStruct(CommandHandlerFactory_CreateBrowserCommandHandler_Params, params_);
    var message = builder.finish();
    this.receiver_.accept(message);
  };

  function CommandHandlerFactoryStub(delegate) {
    this.delegate_ = delegate;
  }
  CommandHandlerFactoryStub.prototype.createBrowserCommandHandler = function(handler) {
    return this.delegate_ && this.delegate_.createBrowserCommandHandler && this.delegate_.createBrowserCommandHandler(handler);
  }

  CommandHandlerFactoryStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kCommandHandlerFactory_CreateBrowserCommandHandler_Name:
      var params = reader.decodeStruct(CommandHandlerFactory_CreateBrowserCommandHandler_Params);
      this.createBrowserCommandHandler(params.handler);
      return true;
    default:
      return false;
    }
  };

  CommandHandlerFactoryStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  function validateCommandHandlerFactoryRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kCommandHandlerFactory_CreateBrowserCommandHandler_Name:
        if (!message.expectsResponse() && !message.isResponse())
          paramsClass = CommandHandlerFactory_CreateBrowserCommandHandler_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validateCommandHandlerFactoryResponse(messageValidator) {
    return validator.validationError.NONE;
  }

  var CommandHandlerFactory = {
    name: 'browser_command.mojom.CommandHandlerFactory',
    kVersion: 0,
    ptrClass: CommandHandlerFactoryPtr,
    proxyClass: CommandHandlerFactoryProxy,
    stubClass: CommandHandlerFactoryStub,
    validateRequest: validateCommandHandlerFactoryRequest,
    validateResponse: null,
  };
  CommandHandlerFactoryStub.prototype.validator = validateCommandHandlerFactoryRequest;
  CommandHandlerFactoryProxy.prototype.validator = null;
  var kCommandHandler_CanExecuteCommand_Name = 1254756948;
  var kCommandHandler_ExecuteCommand_Name = 725311918;

  function CommandHandlerPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(CommandHandler,
                                                   handleOrPtrInfo);
  }

  function CommandHandlerAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        CommandHandler, associatedInterfacePtrInfo);
  }

  CommandHandlerAssociatedPtr.prototype =
      Object.create(CommandHandlerPtr.prototype);
  CommandHandlerAssociatedPtr.prototype.constructor =
      CommandHandlerAssociatedPtr;

  function CommandHandlerProxy(receiver) {
    this.receiver_ = receiver;
  }
  CommandHandlerPtr.prototype.canExecuteCommand = function() {
    return CommandHandlerProxy.prototype.canExecuteCommand
        .apply(this.ptr.getProxy(), arguments);
  };

  CommandHandlerProxy.prototype.canExecuteCommand = function(commandId) {
    var params_ = new CommandHandler_CanExecuteCommand_Params();
    params_.commandId = commandId;
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kCommandHandler_CanExecuteCommand_Name,
          codec.align(CommandHandler_CanExecuteCommand_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(CommandHandler_CanExecuteCommand_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(CommandHandler_CanExecuteCommand_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };
  CommandHandlerPtr.prototype.executeCommand = function() {
    return CommandHandlerProxy.prototype.executeCommand
        .apply(this.ptr.getProxy(), arguments);
  };

  CommandHandlerProxy.prototype.executeCommand = function(commandId, clickInfo) {
    var params_ = new CommandHandler_ExecuteCommand_Params();
    params_.commandId = commandId;
    params_.clickInfo = clickInfo;
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kCommandHandler_ExecuteCommand_Name,
          codec.align(CommandHandler_ExecuteCommand_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(CommandHandler_ExecuteCommand_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(CommandHandler_ExecuteCommand_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function CommandHandlerStub(delegate) {
    this.delegate_ = delegate;
  }
  CommandHandlerStub.prototype.canExecuteCommand = function(commandId) {
    return this.delegate_ && this.delegate_.canExecuteCommand && this.delegate_.canExecuteCommand(commandId);
  }
  CommandHandlerStub.prototype.executeCommand = function(commandId, clickInfo) {
    return this.delegate_ && this.delegate_.executeCommand && this.delegate_.executeCommand(commandId, clickInfo);
  }

  CommandHandlerStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  CommandHandlerStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kCommandHandler_CanExecuteCommand_Name:
      var params = reader.decodeStruct(CommandHandler_CanExecuteCommand_Params);
      this.canExecuteCommand(params.commandId).then(function(response) {
        var responseParams =
            new CommandHandler_CanExecuteCommand_ResponseParams();
        responseParams.canExecute = response.canExecute;
        var builder = new codec.MessageV1Builder(
            kCommandHandler_CanExecuteCommand_Name,
            codec.align(CommandHandler_CanExecuteCommand_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(CommandHandler_CanExecuteCommand_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    case kCommandHandler_ExecuteCommand_Name:
      var params = reader.decodeStruct(CommandHandler_ExecuteCommand_Params);
      this.executeCommand(params.commandId, params.clickInfo).then(function(response) {
        var responseParams =
            new CommandHandler_ExecuteCommand_ResponseParams();
        responseParams.commandExecuted = response.commandExecuted;
        var builder = new codec.MessageV1Builder(
            kCommandHandler_ExecuteCommand_Name,
            codec.align(CommandHandler_ExecuteCommand_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(CommandHandler_ExecuteCommand_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validateCommandHandlerRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kCommandHandler_CanExecuteCommand_Name:
        if (message.expectsResponse())
          paramsClass = CommandHandler_CanExecuteCommand_Params;
      break;
      case kCommandHandler_ExecuteCommand_Name:
        if (message.expectsResponse())
          paramsClass = CommandHandler_ExecuteCommand_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validateCommandHandlerResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kCommandHandler_CanExecuteCommand_Name:
        if (message.isResponse())
          paramsClass = CommandHandler_CanExecuteCommand_ResponseParams;
        break;
      case kCommandHandler_ExecuteCommand_Name:
        if (message.isResponse())
          paramsClass = CommandHandler_ExecuteCommand_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var CommandHandler = {
    name: 'browser_command.mojom.CommandHandler',
    kVersion: 0,
    ptrClass: CommandHandlerPtr,
    proxyClass: CommandHandlerProxy,
    stubClass: CommandHandlerStub,
    validateRequest: validateCommandHandlerRequest,
    validateResponse: validateCommandHandlerResponse,
  };
  CommandHandlerStub.prototype.validator = validateCommandHandlerRequest;
  CommandHandlerProxy.prototype.validator = validateCommandHandlerResponse;
  exports.Command = Command;
  exports.ClickInfo = ClickInfo;
  exports.CommandHandlerFactory = CommandHandlerFactory;
  exports.CommandHandlerFactoryPtr = CommandHandlerFactoryPtr;
  exports.CommandHandlerFactoryAssociatedPtr = CommandHandlerFactoryAssociatedPtr;
  exports.CommandHandler = CommandHandler;
  exports.CommandHandlerPtr = CommandHandlerPtr;
  exports.CommandHandlerAssociatedPtr = CommandHandlerAssociatedPtr;
})();